---
version: "3.8"
services:
  movies:
    image: srinadhgoud/paytmmoviesnetflix:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: srinadhgoud/paytmtrainnetflix:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: srinadhgoud/paytmrechargenetflix:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: srinadhgoud/paytmdthnetflix:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
